version: '3'
services: 
  nginx:
    build: ./Docker/nginx
    working_dir: /var/www/src
    volumes:
      - ./laravel:/var/www/src
      - ./Docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "3000:3000"
      - "3001:3001"
    depends_on: 
      - php-fpm
      
  php-fpm:
    build: ./Docker/php-fpm
    volumes:
      - ./laravel:/var/www/src
    depends_on: 
      - mysql

  mysql:
    image: mysql:5.7.30
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    ## 5.7のデフォルトのsql_modeは以下の通り
    ## ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    ## ONLY_FULL_GROUP_BYだけ省く
    ## https://qiita.com/masayuki14/items/3aa199035eb4fdcfa446
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      TZ: 'Asia/Tokyo'

  node:
    image: node:12.18-alpine3.12
    working_dir: /usr/src/app
    volumes:
      - ./laravel:/usr/src/app
      - ./frontend:/usr/src/frontend
    #ports:
      #- "8080:8080" # http-server
      #- "3000:3000" # BrowserSync
      #- "3001:3001" # BrowserSync
    tty: true