version: '3'
services: 
  nginx:
    build: ./Docker/nginx
    volumes:
      - ./laravel:/var/www/src
      - ./Docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on: 
      - php-fpm
      
  php-fpm:
    build: ./Docker/php-fpm
    volumes:
      - ./laravel:/var/www/src
    depends_on: 
      - mysql

  mysql:
    image: mysql:5.7.30
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      TZ: 'Asia/Tokyo'

  node:
    image: node:12.18-alpine3.12
    working_dir: /usr/src/app
    volumes:
      - ./laravel:/usr/src/app
    tty: true